### ISSUE TITLE
Stop task from different thread?

### ISSUE THREAD

**Issue by daschl** [perfmark/perfmark#3]
Is it possible to stop a task from a different thread where it is started?

To simplify from the readme, something like this:

```java
Future<Response> buildResponse() {
  PerfMark.startTask("Build Response");
    return executor.submit(() -> {
        PerfMark.stopTask("Build Response");
    });
}
```

(Background: I'm starting on the user thread but complete on a netty thread). Thanks!

**Comment by carl-mastrangelo** [comment]
Hi,

I think you may want something else, since gRPC has the same user-thread-to-netty-thread problem.   PerfMark needs the start and stop on same thread, but you can link two tasks together across threads.    The reason for this is that it would be hard to show in the UI a single task between threads, but easy to show the link between two task.    I have an example of how to do this here:  https://github.com/grpc/grpc-java/blob/v1.22.1/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L694

The `onReady` function starts in the Netty thread, but runs a Runnable on the user thread.  They are joined together using the `Link`.

**Comment by carl-mastrangelo** [comment]
Closing due to age, please reopen if you still have questions.
